[project]
name = "shared-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/shared_utils", "src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
